### ISSUE TITLE
Players sometimes attached 1 node too high

### ISSUE THREAD

**Issue by IhrFussel** [tenplus1/mob_horse#1]
Hello, I'm using your mod on my server and it's really great except for one bug:

Sometimes (it seems to happen completely randomly and to all players) when a player wants to ride a horse the game puts the player too high meaning there is ~ 1 node of air between the player and the horse.

I don't know if you can fix it or if it's an engine bug but I wanted to let you know anyways.

**Comment by tenplus1** [comment]
Strange indeed, riding a horse puts the player at the correct level when I test it out, what version of minetest and mobs redo are you using ?

**Comment by IhrFussel** [comment]
I use 0.4.15-dev from Feb 20 on the server

Mobs Redo is the newest version from github (downloaded a few days ago)

Like I said it happens very randomly, sometimes you have to get on/off 50 times before it happens.

**Comment by tenplus1** [comment]
Will keep an eye for it happening but will close the issue for now.
