### ISSUE TITLE
Requesting translation support

### ISSUE THREAD

**Issue by MuhdNurHidayat** [tenplus1/mob_horse#6]
I'm requesting this mod to include translation support like the other mobs redo mods that you've released.

Actually I've tried to add translation support in [my fork](https://github.com/MuhdNurHidayat/mob_horse) of this mod and it do works, but I think you know better on how to actually format the strings to be translator-friendly, so I didn't create PR from my fork.

**Comment by tenplus1** [comment]
added :)
